package model.enums;

public enum Format {
	ONE, TWO, THREE, FOUR, VARIABLE, NONE
}


// VARIABLE AND NONE -> DIRECTIVES ONLY
// THREE AND ONE -> DIRECTIVES AND INSTRUCTIONS
// ONE TWO -> INSTRUCTIONS ONLY